HappyHour/config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'
  post 'users' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'users/:id' => 'users#show', as: :user
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get 'bars/' => 'bars#index'
  get 'bars/new' => 'bars#new', as: :new_bar
  post 'bars/' => 'bars#create'

  get 'bars/:id' => 'bars#show', as: :bar
  get "bars/:id/edit" => "bars#edit", as: :edit_bar
  patch "bars/:id" => "bars#update"
  delete "bars/:id" => "bars#destroy", as: :delete_bar

  get 'bars/:id/offers/' => 'offers#show'
  get 'bars/:id/offers/new' => 'offers#new', as: :bar_offers
  post 'bars/:id/offers/new' => 'offers#create'

  get 'bars/:id/offers/:id/edit' => 'offers#edit', as: :edit_offer
  patch 'bars/:id/offers/:id' => 'offers#update', as: :offer
  delete 'bars/:id/offers/:id' => 'offers#destroy', as: :delete_offer

end

HappyHour/app/models/bar.rb
class Bar < ActiveRecord::Base
  belongs_to :user
  has_many :offers
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>" }, :default_url => "https://s3-us-west-1.amazonaws.com/happyhour-rushi/Bar.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

HappyHour/app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :bar
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>"} , :default_url => "https://s3-us-west-1.amazonaws.com/happyhour-rushi/Bar.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

HappyHour/app/models/user.rb
class User < ActiveRecord::Base
  has_many :bars
  mount_uploader :image, ImageUploader


  attr_reader :password

  def password=(unencrypted_password)
    unless unencrypted_password.empty?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) == unencrypted_password
      return self
    else
      return false
    end
  end

end

HappyHour/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  helper_method :current_user

  private
  #Using || 'pipes' helps us load the database once per page load as opposed to running back to it every method call
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

HappyHour/app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @bars = Bar.all
  end

  def new
    @bar = Bar.new
  end


  def create
    #@user = current_user
    #@bar = @user.bars.new(params)
    @bar = Bar.new(params.require(:bar).permit(:bar_name, :location, :zip, :day, :time, :image, :description))
    @bar.user = current_user
    if @bar.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @bar = Bar.find(params[:id])
  end

  def edit
    @bar = Bar.find(params[:id])
  end

  def update
    @bar = Bar.find(params[:id])

    if @bar.update_attributes(params.require(:bar).permit(:bar_name, :location, :zip, :day, :time, :image, :description))
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end #end update def

  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy
    redirect_to user_path(current_user)
  end


end

HappyHour/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.all
  end

  def new
    @bar = Bar.find(params[:id])
    @offer = @bar.offers.new
  end


  def create
    @bar = Bar.find(params[:id])
    @offer = @bar.offers.new(params.require(:offer).permit(:item, :description, :price, :image))
    #@offer.bar =
    if @offer.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @bar = Bar.find(params[:id])
    @offers = @bar.offers.all
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])

    if @offer.update_attributes(params.require(:offer).permit(:item, :description, :price, :image))
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end #end update def

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to user_path(current_user)
  end


end

HappyHour/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def contact
  end

  def index
  if params[:q]
    @bars = Bar.where("location like ?", '%' + params[:q] + '%')
  elsif params[:r]
    @bars = Bar.where("zip like ?", '%' + params[:r] + '%')
  elsif params[:p]
    @bars = Bar.where("bar_name like ?", '%' + params[:p] + '%')
  elsif params[:s]
    @bars = Bar.where("day like ?", '%' + params[:s] + '%')
  else
    @bars = Bar.all
  end
end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)

      if @user.save
        redirect_to users_path
      else
        render :new
      end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params.require(:user).permit(:name, :password))
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end #end update def


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

HappyHour/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:login][:email])

    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to root_path
    else
      render :new
    end
  end #def create end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

HappyHour/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @bar = Bar.new
  end


  def create
      @user = User.new(user_params)

      if @user.save
        redirect_to root_path
      else
        render :new
      end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params.require(:user).permit(:name, :password))
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end #end update def


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

HappyHour/app/helpers/application_helper.rb
module ApplicationHelper
end

HappyHour/app/helpers/bars_helper.rb
module BarsHelper
end

HappyHour/app/helpers/offers_helper.rb
module OffersHelper
end

HappyHour/app/helpers/pages_helper.rb
module PagesHelper
end

HappyHour/app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id] != nil
  end
end

HappyHour/app/helpers/users_helper.rb
module UsersHelper
end

HappyHour/app/views/bars/edit.html.erb
<div class="jumbotron">
  <h2 class="centeralign"> Edit Your Bar </h2>

  <%= form_for @bar, html: {multipart: true} do |f|  %>
    <div class="form-group">
      <%= f.label :bar_name %>
      <%= f.text_field :bar_name, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :zip %>
      <%= f.text_field :zip, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :day %>
      <%= f.text_field :day, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :time %>
      <%= f.text_field :time, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
      <br>


      <%= f.submit "Update Bar", class: "btn btn-lg btn-default navbar-left" %>

    <%= link_to "Delete Bar", delete_bar_path(@bar), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-lg btn-danger navbar-right" %>
    <br>
    <br>
  <% end %>
</div>

HappyHour/app/views/bars/index.html.erb
<div class="jumbotron">
  <h2>List of Bars</h2>
     <ul>
      <% @bars.each do |bar| %>
        <div class="barlist">
          <li><%= bar.bar_name %></li>
          <%= bar.location %>
          <br>
          <%= bar.zip %>
          <br>
          <%= bar.day %>
        </div>
      <% end %>
    </ul>
</div>

HappyHour/app/views/bars/new.html.erb
<div class="jumbotron">
  <h2 class='centeralign'> Add a Bar! </h2>

  <%= form_for [@user, @bar], html: {multipart: true} do |f|  %>
    <div class="form-group">
      <%= f.label :bar_name %>
      <%= f.text_field :bar_name, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :location %>
      <%= f.text_field :location, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :zip %>
      <%= f.number_field :zip, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :day %>
      <%= f.text_field :day, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :time %>
      <%= f.text_field :time, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
      <br>


      <%= f.submit "Add This Bar!", class: "btn btn-lg btn-default" %>
  <% end %>
</div>

HappyHour/app/views/bars/show.html.erb
<div class="jumbotron">
  <h1><%= @bar.bar_name %> </h1>
</div>

HappyHour/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <!--RS========= Brand and toggle get grouped for better mobile display ============RS-->
  <div class="navbar-header custom-head">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href='/'><strong>Happy Hour</strong></a>
  </div>

  <!--RS========== Collect the nav links, forms, and other content for toggling ===========RS-->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
    <ul class="collapse navbar-collapse nav navbar-nav navbar-right navbar-ex1-collapse">
    <% if logged_in? %>
      <li><a href="/"><%= "Logged in as : #{current_user.name}" %></a>
      <li><%= link_to "Manage My Bars (#{current_user.bars.length})", user_path(current_user) %></li>
      <li><%= link_to 'Add A Bar', new_bar_path %></li>
      <li><%= link_to 'Account Settings', edit_user_path(current_user) %></li>
      <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "For Bar Owners : Sign Up Here", signup_path %></li>
      <li><%= link_to "For Bar Owners : Log In Here", login_path %></li>
    <% end %>
    </ul>
 </div><!-- /.navbar-collapse -->
</nav>

HappyHour/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyHour</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

HappyHour/app/views/offers/edit.html.erb
<div class="jumbotron">
  <h2 class="centeralign"> Edit Your Offer </h2>

  <%= form_for @offer, html: {multipart: true} do |f|  %>
    <div class="form-group">
      <%= f.label :item %>
      <%= f.text_field :item, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
      <br>
      <%= f.submit "Update Offer", class: "navbar-left btn btn-lg btn-default" %>

      <%= link_to "Delete Offer", delete_offer_path(@offer), method: :delete, data: {confirm: "Are you sure?"}, class: "navbar-right btn btn-lg btn-danger" %>
      <br>
      <br>
  <% end %>
</div>

HappyHour/app/views/offers/index.html.erb
<div class="jumbotron">
    <h2>List of Offers</h2>
       <ul>
       <div class="barlist">
        <% @offers.each do |offer| %>
          <div class="offerlist">
            <li><%= offer.item %></li>
            <%= offer.price %>
            <br>
            <%= offer.description %>
            <br>
          </div>
        <% end %>
        </div>
      </ul>
</div>

HappyHour/app/views/offers/new.html.erb
<div class="jumbotron">
  <h2 class='centeralign'> Add an offer to your Bar </h2>

  <%= form_for [@bar, @offer], html: {multipart: true} do |f|  %>
  <form class="form-inline">
    <div class="form-group">
      <%= f.label :item %>
      <%= f.text_field :item, class: "form-control" %>
    </div>
      <br>
        <div class="form-group">
          <div class="input-group">
            <div class="input-group-addon">$</div>
            <%= f.number_field :price, class: "form-control", placeholder: "Price" %>
          </div>
        </div>

      <br>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", size: "25x15" %>
    </div>
      <br>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
      <br>

      <%= f.submit "Add This Offer!", class: "btn btn-lg btn-default" %>
    </form>
  <% end %>
</div>

HappyHour/app/views/offers/show.html.erb
<div class="jumbotron">
  <ul>
    <% @offers.each do |offer| %>
    <p><%= offer.item %></p>
    <p><%= offer.price %></p>
    <p><%= offer.description %></p>
    <% end %>
  </ul>
</div>

HappyHour/app/views/pages/about.html.erb
<div class="jumbotron">
<h1>About Happy Hour</h1>
<p>How many times how you wondered where to grab a drink after work but couldn't decide where? How many times have you over paid for alcohol only to realize there was a One on One offer just a block from where you were?</p>

<p>Introducing HappyHour.... A realtime tracker for all bars and restaurants around you to keep track of the dynamic happy hours around you. This site allows you to view based on location and time all the bars and restaurants that have Happy Hours at that very instant so that you can plan your outing accordingly. It will also show you a comprehensive list of prices so you can compare and pick the place that best suits you.</p>
</div>

HappyHour/app/views/pages/contact.html.erb
<div class="jumbotron">
<h1>Contact Happy Hour</h1>
<p>Thank you for contacting HappyHour</p>
</div>

HappyHour/app/views/pages/index.html.erb
<div class="jumbotron centeralign">
    <h2>Happy Hour</h2>
    <p>Anytime + Anywhere ... Find you the best Happy Hour Deals around you</p>
</div>
    <% if logged_in? %>
    <h2 class="centeralign">List of Bars</h2>
    <form class="form-inline">
      <div class="form-group">
        <%= form_tag(root_path, {method: "get"}) do %>
          <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Search by Location") %>
          <%= submit_tag "Search", class: "btn btn-md btn-default" %>
        <% end %>
        <%= form_tag(root_path, {method: "get"}) do %>
          <%= text_field_tag(:r, nil, class: "form-control", placeholder: "Search by Zip Code") %>
          <%= submit_tag "Search", class: "btn btn-md btn-default" %>
        <% end %>
        <%= form_tag(root_path, {method: "get"}) do %>
          <%= text_field_tag(:s, nil, class: "form-control", placeholder: "Search by HH Day") %>
          <%= submit_tag "Search", class: "btn btn-md btn-default" %>
        <% end %>
        <%= form_tag(root_path, {method: "get"}) do %>
          <%= text_field_tag(:p, nil, class: "form-control", placeholder: "Search by Bar Name") %>
          <%= submit_tag "Search", class: "btn btn-md btn-default" %>
        <% end %>
      </div>
    </form>
       <ul>
        <% @bars.each do |bar| %>
          <div class="barlist">
        <p><h3><%= bar.bar_name %></h3></p>
        <p><%= image_tag bar.image.url %></p>
        <p><strong>Location : </strong><%= bar.location %></p>
        <p><strong>Zip Code : </strong><%= bar.zip %></p>
        <p><strong>Happy Hour Day(s) : </strong><%= bar.day %></p>
        <p><strong>Happy Hour Timings : </strong><%= bar.time %></p>
        <p><strong>Summary : </strong><%= bar.description %></p>
        <% bar.offers.each do |offer| %>
        <div class="barlist">
          <p><%= image_tag offer.image.url(:thumb) %></p>
          <p><strong>Item : </strong><%= offer.item %></p>
          <p><strong>Price : </strong>$<%= offer.price %></p>
          <p><strong>Details : </strong><%= offer.description %></p>
        </div>
        <% end %>
          </div>
        <% end %>
      </ul>
    <% else %>
    <p> Welcome to Happy Hours </p>
    <% end %>



<!--
    <%= text_field_tag(:r, nil, class: "form-control", placeholder: "Search by Zip Code") %>
    <%= submit_tag "Search", class: "btn btn-md btn-default" %>
    <%= text_field_tag(:p, nil, class: "form-control", placeholder: "Search by Bar Name") %>
    <%= submit_tag "Search", class: "btn btn-md btn-default" %>
    <%= text_field_tag(:s, nil, class: "form-control", placeholder: "Search by Happy Hour Day") %>
    <%= submit_tag "Search", class: "btn btn-md btn-default" %> -->

HappyHour/app/views/users/edit.html.erb
<div class="jumbotron">
  <h2 class="centeralign">Account Settings</h2>
  <br>
  <%= form_for @user do |f|  %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control", disabled:true %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <br>
      <div class="centeralign">
      <%= f.submit "Update", class: "btn btn-lg btn-default" %>
      </div>
      <br>
  <% end %>
</div>

HappyHour/app/views/users/new.html.erb
<div class="jumbotron">
  <h2>Sign Up Now</h2>
  <br>
  <%= form_for @user do |f|  %>
    
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <br>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Sign up!", class: "btn btn-lg btn-default" %>
      <br>
  <% end %>
  
</div>

HappyHour/app/views/users/show.html.erb
<div class='jumbotron centeralign'>
  <section>
    <h3>Hey <%= @user.name %>, Here are all of your Bars (<%= @user.bars.length %>)</h3>
  </section>
</div>
  <section>
    <h3>Bars</h3>

    <% @user.bars.each do |bar| %>
      <div class="barlistself">
        <p><strong>Bar Name : <%= bar.bar_name %></strong></p>
        <p><%= image_tag(bar.image.url) %></p>
        <p><strong>Bar Location : <%= bar.location %></strong></p>
        <p><strong>Zip Code : <%= bar.zip %></strong></p>
        <p><strong>Day of the week : <%= bar.day %></strong></p>
        <p><strong>Happy Hour Timings : <%= bar.time %></strong></p>
        <p><strong>Bar Description : <%= bar.description %></strong></p>
        <p><strong>Number of Offers : <%= bar.offers.length %></strong></p>
        <span class='edbutton'><%= link_to "Edit Bar", edit_bar_path(bar), class: "btn btn-primary" %></span>
        <span class='edbutton'><%= link_to "Add Offer", bar_offers_path(bar), class: "btn btn-warning" %></span>
        <h3>Offers</h3>
        <% bar.offers.each do |offer| %>
        <div class="offerlist">
          <p><%= image_tag offer.image.url(:thumb) %></p>
          <p><strong>Item : <%= offer.item %></strong></p>
          <p><strong>Price : $<%= offer.price %></strong></p>
          <p><strong>Description : <%= offer.description %></strong></p>
          <span class='edbutton'><%= link_to "Edit Offer", edit_offer_path(offer), class: "btn btn-md btn-success" %></span>
        </div>
        <% end %>
      </div>
    <% end %>
  </section>